[package]
name = "accounts"
version = "0.1.1"
authors = ["jackedgson <jack@jackedgson.com>"]
edition = "2021"

[dependencies]
async-graphql = "3.0"
async-graphql-warp = "3.0"
async-trait = "0.1.52"
tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread"] }
warp = "0.3"
