# Configuration of the router's HTTP server
server:
  # The socket address and port to listen on
  # Defaults to 127.0.0.1:4000
  listen: 127.0.0.1:4000

  # Cross origin request headers
  cors:
    # Set to false to disallow any origin and rely exclusively on `origins`
    # Defaults to true
    allow_any_origin: true
    # List of accepted origins
    # origins:
      # - https://studio.apollographql.com
    # Set to true to add the `Access-Control-Allow-Credentials` header
    allow_credentials: false
    # The headers to allow.
    # Defaults to the required request header for Apollo Studio: Content-Type
    allow_headers: [ Content-Type ]
    # Allowed request methods
    # Defaults to GET, POST, OPTIONS.
    methods: [ GET, POST, OPTIONS ]
    # Which response headers should be made available to scripts running in the browser,
    # in response to a cross-origin request.
    expose_headers: